# .streamlit/secrets.toml

# The actual key used for API calculation calls
GEMINI_API_KEY = "AIzaSyYourActualAPIKeyHere_xxxxxxxxxxxx"

# The text anyone can type into the app screen box
APP_ACCESS_PASSWORD = "AmaravatiHealth2026!"
